variable "format_map" {
  type        = map(string)
  description = "Map of naming convention format"
}

variable "format_values" {
  type        = map(string)
  description = "Map of naming convention values"
}

variable "project_id" {
  type        = string
  description = "Project ID"
}

variable "location" {
  type        = string
  description = "Location. eg: EU"
}

variable "region" {
  type        = string
  description = "Region. eg: europe-west1"
}

variable "zone" {
  type        = string
  description = "Zone. eg: europe-west1-b"
}

variable "name" {
  type        = string
  description = "Dataiku deployment name"
}

variable "shared_vpc_project_id" {
  type        = string
  description = "Shared VPC project ID"
}

variable "shared_vpc_name" {
  type        = string
  description = "Shared VPC project name"
}

variable "shared_vpc_subnet_region" {
  type        = string
  description = "Shared VPC subnet region"
}

variable "shared_vpc_subnet_name" {
  type        = string
  description = "Shared VPC subnet name"
}

variable "ssl_certificate_secret_id" {
  type        = string
  description = "Google Secret Manager SSL certificate secret ID containing the SSL certificate value in PEM format"
}

variable "ssl_private_key_secret_id" {
  type        = string
  description = "Google Secret Manager SSL private key secret ID containing the SSL private key value in PEM format"
}

variable "data_disk_size" {
  type        = number
  description = "Data disk size in GB for the Compute Engine instance. The GigaByte available to store Dataiku resources in the machine. The default value suits most of needs."
  default     = 1000
}

variable "dataiku_setup_version" {
  type        = string
  description = "Dataiku setup script version used to provision the Dataiku machine. Please go to https://github.com/lvmh-data/atom-dataiku-setup for more information."
  default     = "12.6.3"
}

variable "node_type" {
  type        = string
  description = "Dataiku node type. It can be 'design', 'automation' or 'api'. See more here: https://doc.dataiku.com/dss/latest/deployment/index.html."
  default     = "design"
}

variable "okta_domain" {
  type        = string
  description = "Okta domain. Your Okta domain (URL), looks like: `example.okta.com`, `okta.lvmh.com`... "
}

variable "oidc_client_id" {
  type        = string
  description = "OIDC client ID. The client ID generated by the IdP (Okta), enter the raw value."
}

variable "oidc_client_secret_name" {
  type        = string
  description = "OIDC client secret name containing the client secret value generated by the IdP. The secret's value shall not start with a hyphen '-'"
}

variable "dss_admin_email" {
  type        = string
  description = "DSS admin email, it will be used as the first available mean of login to finalize the DSS configuration."
}

variable "apt_proxy_url" {
  type        = string
  description = "APT proxy URL"
  default     = "http://emea-private-zscaler.proxy.lvmh:9480"
}

variable "sentinel_one_token_name" {
  type        = string
  description = "Sentinel one secret token name containing the SentinelOne site token. Used to install SentinelOne on the Dataiku machine, each Maison has a dedicated site token. If not provided neither Tanium nor SentineOne will be installed on the Dataiku VM."
  default     = "FALSE"
}

variable "tanium_tags" {
  type        = string
  description = "Tanium tags pass to the VM."
  default     = "FALSE"
}

variable "dataiku_license_secret_name" {
  type        = string
  description = "Name of secret containing Dataiku license in json format. Mandatory for Dataiku api node. It is use to set a license automatically when installing Dataiku."
}

variable "machine_type" {
  type        = string
  description = "Machine type used for the Compute Engine instance hosting Dataiku. It will affect the compute power available for running jobs with the DSS."
  default     = "n1-standard-2"
}

variable "cloud_sql_instance_connection_name" {
  type        = string
  description = "Name of the connection of a Cloud SQL instance to use for hosting the Dataiku internal database ('project_id:region:instance_name')."
  default     = ""
}

variable "cloud_sql_dataiku_password_secret_name" {
  type        = string
  description = "Name of the secret containing the password of the 'dataiku' user of the Cloud SQL instance."
  default     = ""
}

variable "gke_node_pools" {
  type = map(object({
    max_node_count = number
    machine_type   = string
    gpu_type       = string
    gpu_count      = number
  }))
  default     = {}
  description = "Map with k8s node-pool details"
}

variable "source_data_disk" {
  type        = string
  description = "Fusion: Source disk to import (copy). Old-Dataiku data disk to use as a source for the Dataiku deployed. Format: 'zones/{zone}/disks/{disk}' or 'regions/{region}/disks/{disk}'"
  default     = ""
}

variable "source_data_disk_type" {
  type        = string
  description = "Fusion: To import a regional persistent disk you must specify its type otherwise the deployment will fail if it isn't a 'pd-standard'"
  default     = "pd-standard"
}

variable "source_storage_bucket" {
  type = object({
    name     = string
    location = string
  })
  description = "Fusion: Storage bucket to import (no-copy). Old-Dataiku GCS bucket to import for the Dataiku deployed."
  default     = null
}

variable "source_bigquery_dataset" {
  type = object({
    dataset_id    = string
    location      = string
    friendly_name = string
    description   = string
  })
  description = "Fusion: BigQuery dataset to import (no-copy). Old-Dataiku bigquery dataset to import for the Dataiku deployed."
  default     = null
}

variable "start_stop" {
  type = object({
    time_zone  = string
    start_time = string
    stop_time  = string
  })
  description = "Start/Stop schedule (cron format)"
  default     = null
}
